In [1]:
import re
from pathlib import Path
import numpy as np
import pandas as pd

import configparser, s3fs

from core import TS_L_PARAMS, INFO_DATAFRAME_MAPPING

In [2]:
cred_file = "/home/exouser/.config/rclone/rclone.conf"

In [4]:
# Get cloud bucket
config = configparser.ConfigParser()
config.read(cred_file)
fs = s3fs.S3FileSystem(
    key=config["osn_sdsc_hake"]["access_key_id"],
    secret=config["osn_sdsc_hake"]["secret_access_key"],
    client_kwargs={"endpoint_url": config["osn_sdsc_hake"]["endpoint"]},
)

In [5]:
path_main = "/media/volume/shimada_202506_volume/trawl" # path to local processed trawl info
path_bio_files = "agr230002-bucket01/prefect_sh2506_test/trawl" # path to cloud trawl data

In [6]:
fs.glob(f"{path_bio_files}/*/*_LFdata.xlsx")

['agr230002-bucket01/prefect_sh2506_test/trawl/LengthFreq/002_LFdata.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/LengthFreq/003_LFdata.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/LengthFreq/004_LFdata.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/LengthFreq/005_LFdata.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/LengthFreq/007_LFdata.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/LengthFreq/008_LFdata.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/LengthFreq/009_LFdata.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/LengthFreq/010_LFdata.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/LengthFreq/011_LFdata.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/LengthFreq/012_LFdata.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/LengthFreq/013_LFdata.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/LengthFreq/014_LFdata.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/LengthFreq/015_LFdata.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/LengthFreq/016_LFdata.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/LengthFreq/017_LFdata.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/LengthFreq/018_LFdata.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/LengthFreq/019_LFdata.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/LengthFreq/020_LFdata.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/LengthFreq/021_LFdata.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/LengthFreq/022_LFdata.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/LengthFreq/023_LFdata.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/LengthFreq/024_LFdata.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/LengthFreq/025_LFdata.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/LengthFreq/026_LFdata.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/LengthFreq/027_LFdata.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/LengthFreq/028_LFdata.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/LengthFreq/029_LFdata.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/LengthFreq/032_LFdata.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/LengthFreq/033_LFdata.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/LengthFreq/034_LFdata.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/LengthFreq/035_LFdata.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/LengthFreq/036_LFdata.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/LengthFreq/038_LFdata.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/LengthFreq/039_LFdata.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/LengthFreq/040_LFdata.xlsx']

In [7]:
fs.glob(f"{path_bio_files}/*/*_specimens.xlsx")

['agr230002-bucket01/prefect_sh2506_test/trawl/Specimens/002_specimens.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/Specimens/003_specimens.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/Specimens/004_specimens.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/Specimens/005_specimens.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/Specimens/007_specimens.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/Specimens/008_specimens.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/Specimens/009_specimens.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/Specimens/010_specimens.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/Specimens/011_specimens.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/Specimens/012_specimens.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/Specimens/013_specimens.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/Specimens/014_specimens.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/Specimens/015_specimens.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/Specimens/016_specimens.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/Specimens/017_specimens.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/Specimens/018_specimens.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/Specimens/019_specimens.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/Specimens/020_specimens.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/Specimens/021_specimens.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/Specimens/022_specimens.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/Specimens/023_specimens.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/Specimens/024_specimens.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/Specimens/025_specimens.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/Specimens/026_specimens.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/Specimens/027_specimens.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/Specimens/028_specimens.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/Specimens/029_specimens.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/Specimens/032_specimens.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/Specimens/033_specimens.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/Specimens/034_specimens.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/Specimens/035_specimens.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/Specimens/036_specimens.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/Specimens/038_specimens.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/Specimens/039_specimens.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/Specimens/040_specimens.xlsx']

In [8]:
fs.glob(f"{path_bio_files}/*/*_CatchPerc.xlsx")

['agr230002-bucket01/prefect_sh2506_test/trawl/CatchPercentages/002_CatchPerc.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/CatchPercentages/003_CatchPerc.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/CatchPercentages/004_CatchPerc.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/CatchPercentages/005_CatchPerc.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/CatchPercentages/007_CatchPerc.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/CatchPercentages/008_CatchPerc.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/CatchPercentages/009_CatchPerc.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/CatchPercentages/010_CatchPerc.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/CatchPercentages/011_CatchPerc.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/CatchPercentages/012_CatchPerc.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/CatchPercentages/013_CatchPerc.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/CatchPercentages/014_CatchPerc.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/CatchPercentages/015_CatchPerc.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/CatchPercentages/016_CatchPerc.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/CatchPercentages/017_CatchPerc.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/CatchPercentages/018_CatchPerc.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/CatchPercentages/019_CatchPerc.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/CatchPercentages/020_CatchPerc.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/CatchPercentages/021_CatchPerc.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/CatchPercentages/022_CatchPerc.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/CatchPercentages/023_CatchPerc.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/CatchPercentages/024_CatchPerc.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/CatchPercentages/025_CatchPerc.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/CatchPercentages/026_CatchPerc.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/CatchPercentages/027_CatchPerc.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/CatchPercentages/028_CatchPerc.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/CatchPercentages/029_CatchPerc.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/CatchPercentages/030_CatchPerc.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/CatchPercentages/032_CatchPerc.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/CatchPercentages/033_CatchPerc.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/CatchPercentages/034_CatchPerc.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/CatchPercentages/035_CatchPerc.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/CatchPercentages/036_CatchPerc.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/CatchPercentages/037_CatchPerc.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/CatchPercentages/038_CatchPerc.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/CatchPercentages/039_CatchPerc.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/CatchPercentages/040_CatchPerc.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/CatchPercentages/041_CatchPerc.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/CatchPercentages/042_CatchPerc.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/CatchPercentages/044_CatchPerc.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/CatchPercentages/~$044_CatchPerc.xlsx']

In [13]:
fs.glob(f"{path_bio_files}/*/*_NetConfig.xlsx")

['agr230002-bucket01/prefect_sh2506_test/trawl/NetConfig/202506_001_NetConfig.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/NetConfig/202506_002_NetConfig.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/NetConfig/202506_003_NetConfig.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/NetConfig/202506_004_NetConfig.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/NetConfig/202506_005_NetConfig.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/NetConfig/202506_006_NetConfig.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/NetConfig/202506_007_NetConfig.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/NetConfig/202506_008_NetConfig.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/NetConfig/202506_009_NetConfig.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/NetConfig/202506_010_NetConfig.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/NetConfig/202506_011_NetConfig.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/NetConfig/202506_012_NetConfig.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/NetConfig/202506_013_NetConfig.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/NetConfig/202506_014_NetConfig.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/NetConfig/202506_015_NetConfig.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/NetConfig/202506_016_NetConfig.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/NetConfig/202506_017_NetConfig.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/NetConfig/202506_018_NetConfig.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/NetConfig/202506_019_NetConfig.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/NetConfig/202506_020_NetConfig.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/NetConfig/202506_021_NetConfig.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/NetConfig/202506_022_NetConfig.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/NetConfig/202506_023_NetConfig.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/NetConfig/202506_024_NetConfig.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/NetConfig/202506_025_NetConfig.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/NetConfig/202506_026_NetConfig.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/NetConfig/202506_027_NetConfig.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/NetConfig/202506_028_NetConfig.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/NetConfig/202506_029_NetConfig.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/NetConfig/202506_030_NetConfig.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/NetConfig/202506_031_NetConfig.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/NetConfig/202506_032_NetConfig.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/NetConfig/202506_033_NetConfig.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/NetConfig/202506_034_NetConfig.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/NetConfig/202506_035_NetConfig.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/NetConfig/202506_036_NetConfig.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/NetConfig/202506_037_NetConfig.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/NetConfig/202506_038_NetConfig.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/NetConfig/202506_039_NetConfig.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/NetConfig/202506_040_NetConfig.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/NetConfig/202506_041_NetConfig.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/NetConfig/202506_042_NetConfig.xlsx',
 'agr230002-bucket01/prefect_sh2506_test/trawl/NetConfig/202506_044_NetConfig.xlsx']

In [46]:
bio_filenames = {
    "length": fs.glob(f"{path_bio_files}/*/*_LFdata.xlsx"),
    "specimen": fs.glob(f"{path_bio_files}/*/*_specimens.xlsx"),
    "catch": fs.glob(f"{path_bio_files}/*/*_CatchPerc.xlsx"),
    "info": fs.glob(f"{path_bio_files}/*/*_NetConfig.xlsx"),
}

In [22]:
HAUL_NUM_PATTERN = rf"(\w+)?(?P<haul_num>\d{{3}})_\w+\.xlsx"

In [26]:
re.match(HAUL_NUM_PATTERN, "032_LFdata.xlsx").group("haul_num")

'032'

In [25]:
re.match(HAUL_NUM_PATTERN, "202506_032_NetConfig.xlsx").group("haul_num")

'032'

In [47]:
HAUL_NUM_PATTERN = rf"(\w+)?(?P<haul_num>\d{{3}})_\w+\.xlsx"
haul_num_all = {k: set() for k in bio_filenames.keys()}
for file_type in bio_filenames.keys():
    for fname in bio_filenames[file_type]:
        match_str = re.match(HAUL_NUM_PATTERN, Path(fname).name)
        if match_str is not None:
            haul_num_all[file_type].add(int(match_str["haul_num"]))

In [49]:
valid_hauls = set.union(*haul_num_all.values())
haul_num_to_remove = set()
for file_type in bio_filenames.keys():
    haul_num_diff = valid_hauls.difference(haul_num_all[file_type])
    if haul_num_diff:
        haul_num_to_remove.update(haul_num_diff)
valid_hauls.difference_update(haul_num_to_remove)

In [50]:
valid_hauls

{2,
 3,
 4,
 5,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 32,
 33,
 34,
 35,
 36,
 38,
 39,
 40}

In [52]:
file_haul_info_all = Path(path_main) / "haul_info_all.csv"

In [53]:
hauls_valid = valid_hauls

In [54]:
# Get hauls to process
if not file_haul_info_all.exists():
    df_haul_info_all = pd.DataFrame()
    hauls_processed = set()
else:            
    df_haul_info_all = pd.read_csv(file_haul_info_all, index_col=0)
    hauls_processed = set(df_haul_info_all["operation_number"].unique())
hauls_to_process = list(hauls_valid.difference(hauls_processed))

In [85]:
df_length = []
df_specimen = []
df_info = []
for haul_num in hauls_to_process:
    with fs.open(f"{path_bio_files}/LengthFreq/{haul_num:03d}_LFdata.xlsx") as f:
        df_length.append(
            pd.read_excel(f, index_col=0, sheet_name="Codend")
            .reset_index().assign(haul_num=haul_num)
        )
    with fs.open(f"{path_bio_files}/Specimens/{haul_num:03d}_specimens.xlsx") as f:
        df_specimen.append(
            pd.read_excel(f, index_col=0, sheet_name="Codend")
            .reset_index().assign(haul_num=haul_num)
        )
    with fs.open(f"{path_bio_files}/NetConfig/202506_{haul_num:03d}_NetConfig.xlsx") as f:
        df_info_temp = pd.read_excel(f, index_col=0, sheet_name="ButtonPresses").reset_index()
        df_info.append(
            # reset index to get haul number into a column
            df_info_temp[df_info_temp["button"] == "NIW"][["haul", "time_stamp", "Latitude", "Longitude"]]
        )
df_length = pd.concat(df_length, ignore_index=True)
df_specimen = pd.concat(df_specimen, ignore_index=True)
df_info = pd.concat(df_info, ignore_index=True)

In [87]:
df_length

     length  Female  Male  Unsexed  Sum  haul_num
0         4     0.0     0      1.0    1         2
1         6     0.0     0      1.0    1         2
2        18     0.0     0      1.0    1         2
3        19     0.0     1      0.0    1         2
4        20     3.0     2      5.0   10         2
..      ...     ...   ...      ...  ...       ...
657      49     5.0     1      NaN    6        40
658      50     1.0     1      NaN    2        40
659      51     2.0     2      NaN    4        40
660      53     3.0     0      NaN    3        40
661      66     1.0     0      NaN    1        40

[662 rows x 6 columns]

In [88]:
df_specimen["rounded_length"] = df_specimen["fork_length"].round(0)

In [89]:
df_specimen

,SPECIMEN_ID,fork_length,organism_weight,sex,haul_num,rounded_length
0,119,28.8,0.130,Female,2,29.0
1,242,24.4,0.094,Male,2,24.0
2,262,30.5,0.174,Female,2,30.0
3,263,21.3,0.062,Female,2,21.0
4,282,19.9,0.052,Female,2,20.0
...,...,...,...,...,...,...
1570,18025,45.9,0.590,Male,40,46.0
1571,18026,38.5,0.410,Female,40,38.0
1572,18027,45.3,0.588,Male,40,45.0
1573,18028,37.8,0.342,Female,40,38.0
1574,18029,35.1,0.262,Male,40,35.0

In [90]:
df_specimen.groupby(["sex", "rounded_length", "haul_num"]).size().reset_index(name="frequency")

         sex  rounded_length  haul_num  frequency
0     Female            18.0         4          5
1     Female            19.0         2          1
2     Female            19.0         4          4
3     Female            20.0         2          2
4     Female            20.0         4          5
..       ...             ...       ...        ...
595     Male            52.0        34          1
596  Unsexed            23.0        15          1
597  Unsexed            25.0         8          1
598  Unsexed            26.0        22          1
599  Unsexed            31.0         8          1

[600 rows x 4 columns]

In [106]:
haul_num = 2
with fs.open(f"{path_bio_files}/LengthFreq/{haul_num:03d}_LFdata.xlsx") as f:
    df_length_temp = pd.read_excel(f, index_col=0, sheet_name="Codend").reset_index().drop("Sum", axis=1)
df_length_temp

    length  Female  Male  Unsexed
0        4       0     0        1
1        6       0     0        1
2       18       0     0        1
3       19       0     1        0
4       20       3     2        5
5       21       2     7       10
6       22      10    11       13
7       23      13    13        3
8       24       4     9        0
9       25       0     3        0
10      26       3     2        0
11      27       0     1        0
12      28       6     0        0
13      29       6     2        0
14      30       3     2        0
15      31       3     1        0
16      32       1     1        0
17      33       3     0        0
18      35       2     0        0

In [98]:
df_long = df_length_haul2.melt(
    id_vars=["length"], 
    value_vars=["Male", "Female", "Unsexed"], 
    var_name="sex", 
    value_name="frequency"
)
# Convert frequency column to integer type
df_long["frequency"] = df_long["frequency"].fillna(0).astype(int)
df_long

    length      sex  frequency
0        4     Male          0
1        6     Male          0
2       18     Male          0
3       19     Male          1
4       20     Male          2
5       21     Male          7
6       22     Male         11
7       23     Male         13
8       24     Male          9
9       25     Male          3
10      26     Male          2
11      27     Male          1
12      28     Male          0
13      29     Male          2
14      30     Male          2
15      31     Male          1
16      32     Male          1
17      33     Male          0
18      35     Male          0
19       4   Female          0
20       6   Female          0
21      18   Female          0
22      19   Female          0
23      20   Female          3
24      21   Female          2
25      22   Female         10
26      23   Female         13
27      24   Female          4
28      25   Female          0
29      26   Female          3
30      27   Female          0
31      28   Female          6
32      29   Female          6
33      30   Female          3
34      31   Female          3
35      32   Female          1
36      33   Female          3
37      35   Female          2
38       4  Unsexed          1
39       6  Unsexed          1
40      18  Unsexed          1
41      19  Unsexed          0
42      20  Unsexed          5
43      21  Unsexed         10
44      22  Unsexed         13
45      23  Unsexed          3
46      24  Unsexed          0
47      25  Unsexed          0
48      26  Unsexed          0
49      27  Unsexed          0
50      28  Unsexed          0
51      29  Unsexed          0
52      30  Unsexed          0
53      31  Unsexed          0
54      32  Unsexed          0
55      33  Unsexed          0
56      35  Unsexed          0

In [100]:
df_length_temp

   length  Male  Sum
0      36     2    2

In [118]:
df_length = []
df_specimen = []
df_info = []
for haul_num in hauls_to_process:
    with fs.open(f"{path_bio_files}/LengthFreq/{haul_num:03d}_LFdata.xlsx") as f:
        df_length_temp = pd.read_excel(f, index_col=0, sheet_name="Codend").reset_index().drop("Sum", axis=1)
        df_length_temp = df_length_temp.melt(
            id_vars=["length"],
            # value_vars=["Male", "Female", "Unsexed"], 
            var_name="sex", 
            value_name="frequency"
        ).assign(haul_num=haul_num)
        df_length_temp["frequency"] = df_length_temp["frequency"].fillna(0).astype(int)                
        df_length.append(df_length_temp)
    with fs.open(f"{path_bio_files}/Specimens/{haul_num:03d}_specimens.xlsx") as f:
        df_specimen.append(
            pd.read_excel(f, index_col=0, sheet_name="Codend")
            .reset_index().assign(haul_num=haul_num)
        )
    with fs.open(f"{path_bio_files}/NetConfig/202506_{haul_num:03d}_NetConfig.xlsx") as f:
        df_info_temp = pd.read_excel(f, index_col=0, sheet_name="ButtonPresses").reset_index()
        df_info.append(
            # reset index to get haul number into a column
            df_info_temp[df_info_temp["button"] == "NIW"][["haul", "time_stamp", "Latitude", "Longitude"]]
        )
df_length = pd.concat(df_length, ignore_index=True)
df_specimen = pd.concat(df_specimen, ignore_index=True)
df_info = pd.concat(df_info, ignore_index=True)

In [119]:
df_length

      length     sex  frequency  haul_num
0          4  Female          0         2
1          6  Female          0         2
2         18  Female          0         2
3         19  Female          0         2
4         20  Female          3         2
...      ...     ...        ...       ...
1711      49    Male          1        40
1712      50    Male          1        40
1713      51    Male          2        40
1714      53    Male          0        40
1715      66    Male          0        40

[1716 rows x 4 columns]

In [120]:
df_specimen

      SPECIMEN_ID  fork_length  organism_weight     sex  haul_num
0             119         28.8            0.130  Female         2
1             242         24.4            0.094    Male         2
2             262         30.5            0.174  Female         2
3             263         21.3            0.062  Female         2
4             282         19.9            0.052  Female         2
...           ...          ...              ...     ...       ...
1570        18025         45.9            0.590    Male        40
1571        18026         38.5            0.410  Female        40
1572        18027         45.3            0.588    Male        40
1573        18028         37.8            0.342  Female        40
1574        18029         35.1            0.262    Male        40

[1575 rows x 5 columns]

In [126]:
# Round fish length to nearest integer
df_specimen["length"] = df_specimen["fork_length"].round(0).astype(int)                

# Get length count from both dataframes
specimen_counts = (
    df_specimen.groupby(["sex", "length", "haul_num"]).size()
    .reset_index(name="frequency")
)
length_counts = (
    df_length.groupby(["sex", "length", "haul_num"])
    .agg({"frequency": "sum"}).reset_index()
)

In [127]:
df_specimen

      SPECIMEN_ID  fork_length  organism_weight     sex  haul_num  length
0             119         28.8            0.130  Female         2      29
1             242         24.4            0.094    Male         2      24
2             262         30.5            0.174  Female         2      30
3             263         21.3            0.062  Female         2      21
4             282         19.9            0.052  Female         2      20
...           ...          ...              ...     ...       ...     ...
1570        18025         45.9            0.590    Male        40      46
1571        18026         38.5            0.410  Female        40      38
1572        18027         45.3            0.588    Male        40      45
1573        18028         37.8            0.342  Female        40      38
1574        18029         35.1            0.262    Male        40      35

[1575 rows x 6 columns]

In [128]:
specimen_counts

         sex  length  haul_num  frequency
0     Female      18         4          5
1     Female      19         2          1
2     Female      19         4          4
3     Female      20         2          2
4     Female      20         4          5
..       ...     ...       ...        ...
595     Male      52        34          1
596  Unsexed      23        15          1
597  Unsexed      25         8          1
598  Unsexed      26        22          1
599  Unsexed      31         8          1

[600 rows x 4 columns]

In [129]:
length_counts = df_length.groupby(["sex", "length", "haul_num"]).agg({"frequency": "sum"}).reset_index()
length_counts

          sex  length  haul_num  frequency
0      Female       0        23          1
1      Female       4         2          0
2      Female       5         4          0
3      Female       6         2          0
4      Female       6         4          0
...       ...     ...       ...        ...
1711  Unsexed      66        34          0
1712  Unsexed      71        34          0
1713  Unsexed      72        34          0
1714  Unsexed      75        13          0
1715  Unsexed     102         4          0

[1716 rows x 4 columns]

In [130]:
df_combined = pd.merge(
    specimen_counts.reset_index(),
    length_counts.reset_index(),
    on=["sex", "length", "haul_num"],
    how="outer"
).fillna(0)

In [131]:
df_combined

      index_x      sex  length  haul_num  frequency_x  index_y  frequency_y
0         0.0   Female       0        23          0.0      0.0          1.0
1         0.0   Female       4         2          0.0      1.0          0.0
2         0.0   Female       5         4          0.0      2.0          0.0
3         0.0   Female       6         2          0.0      3.0          0.0
4         0.0   Female       6         4          0.0      4.0          0.0
...       ...      ...     ...       ...          ...      ...          ...
1733      0.0  Unsexed      66        34          0.0   1711.0          0.0
1734      0.0  Unsexed      71        34          0.0   1712.0          0.0
1735      0.0  Unsexed      72        34          0.0   1713.0          0.0
1736      0.0  Unsexed      75        13          0.0   1714.0          0.0
1737      0.0  Unsexed     102         4          0.0   1715.0          0.0

[1738 rows x 7 columns]

In [132]:
df_combined["frequency"] = (df_combined["frequency_x"] + df_combined["frequency_y"]).astype(int)

In [133]:
df_combined

,index_x,sex,length,haul_num,frequency_x,index_y,frequency_y,frequency
0,0.0,Female,0,23,0.0,0.0,1.0,1
1,0.0,Female,4,2,0.0,1.0,0.0,0
2,0.0,Female,5,4,0.0,2.0,0.0,0
3,0.0,Female,6,2,0.0,3.0,0.0,0
4,0.0,Female,6,4,0.0,4.0,0.0,0
...,...,...,...,...,...,...,...,...
1733,0.0,Unsexed,66,34,0.0,1711.0,0.0,0
1734,0.0,Unsexed,71,34,0.0,1712.0,0.0,0
1735,0.0,Unsexed,72,34,0.0,1713.0,0.0,0
1736,0.0,Unsexed,75,13,0.0,1714.0,0.0,0
1737,0.0,Unsexed,102,4,0.0,1715.0,0.0,0

In [134]:
df_combined[["sex", "length", "frequency", "haul_num"]]

          sex  length  frequency  haul_num
0      Female       0          1        23
1      Female       4          0         2
2      Female       5          0         4
3      Female       6          0         2
4      Female       6          0         4
...       ...     ...        ...       ...
1733  Unsexed      66          0        34
1734  Unsexed      71          0        34
1735  Unsexed      72          0        34
1736  Unsexed      75          0        13
1737  Unsexed     102          0         4

[1738 rows x 4 columns]

In [135]:
df_info

    haul              time_stamp   Latitude   Longitude
0      2 2025-06-14 19:05:54.064  33.158825 -117.435728
1      3 2025-06-15 22:29:43.901  32.868391 -118.729643
2      4 2025-06-18 00:04:18.016  33.835924 -118.421470
3      5 2025-06-19 19:46:59.687  33.546128 -119.724851
4      7 2025-06-23 14:10:54.855  34.111264 -120.142156
5      8 2025-07-03 23:15:09.334  34.504013 -121.267087
6      9 2025-07-05 01:14:34.995  34.995782 -121.430632
7     10 2025-07-06 16:16:01.549  35.028608 -120.982071
8     11 2025-07-07 17:38:13.931  35.536348 -121.207317
9     12 2025-07-08 00:09:42.940  35.501723 -121.783373
10    13 2025-07-08 16:35:13.188  35.988864 -121.618275
11    14 2025-07-08 20:50:53.792  36.007926 -121.795800
12    15 2025-07-09 22:44:56.816  36.509396 -122.275019
13    16 2025-07-10 20:08:20.141  36.506992 -121.990075
14    17 2025-07-12 16:00:43.294  36.999511 -122.592690
15    18 2025-07-12 19:42:22.181  37.017300 -122.581100
16    19 2025-07-13 20:13:57.593  37.527514 -122.978011
17    20 2025-07-14 20:32:38.596  37.768300 -123.251800
18    21 2025-07-20 18:37:07.144  38.266222 -123.497869
19    22 2025-07-22 17:02:42.159  39.018801 -123.921408
20    23 2025-07-23 14:41:31.417  39.249200 -123.952900
21    24 2025-07-24 15:40:30.962  39.766896 -124.084808
22    25 2025-07-25 17:20:44.365  40.023404 -124.189600
23    26 2025-07-25 21:33:30.895  40.030300 -124.197100
24    27 2025-07-26 22:31:27.824  40.575022 -124.734109
25    28 2025-07-27 16:25:03.809  40.754019 -124.567688
26    29 2025-07-28 21:55:49.744  41.259599 -124.420790
27    32 2025-07-30 14:47:13.255  41.512250 -124.853550
28    33 2025-08-12 17:53:19.541  42.030284 -124.540561
29    34 2025-08-19 15:31:19.971  42.537132 -124.620950
30    35 2025-08-19 21:55:08.962  42.497288 -125.131317
31    36 2025-08-20 18:47:10.230  42.989183 -124.893507
32    38 2025-08-22 23:45:04.364  43.750601 -124.600679
33    39 2025-08-29 15:45:13.055  44.090387 -125.064918
34    40 2025-08-29 19:33:08.848  43.998004 -124.934579

In [136]:
df_length_count = df_combined[["sex", "length", "frequency", "haul_num"]]

In [139]:
df_specimen.rename(columns={"haul_num": "haul"}, inplace=True)
df_specimen = pd.merge(
    df_specimen,
    df_info,
    on="haul",
    how="left"
)

In [140]:
df_length.rename(columns={"haul_num": "haul"}, inplace=True)
df_length = pd.merge(
    df_length,
    df_info,
    on="haul",
    how="left"
)

In [142]:
df_length_count.rename(columns={"haul_num": "haul"}, inplace=True)
df_length_count = pd.merge(
    df_length_count,
    df_info,
    on="haul",
    how="left"
)

In [146]:
file_haul_info_all = Path(path_main) / "haul_info_all.csv"
file_specimen_all = Path(path_main) / "specimen_all.csv"
file_length_all = Path(path_main) / "length_all.csv"
file_length_count_all = Path(path_main) / "length_count_all.csv"
file_stratum_mean = Path(path_main) / "stratum_mean.csv"

In [147]:
# Update df_haul_info_all, df_specimen_all, df_length_all
df_specimen_all = pd.read_csv(file_specimen_all, index_col=0) if file_specimen_all.exists() else pd.DataFrame()
df_length_all = pd.read_csv(file_length_all, index_col=0) if file_length_all.exists() else pd.DataFrame()
df_length_count_all = pd.read_csv(file_length_count_all, index_col=0) if file_length_count_all.exists() else pd.DataFrame()
df_haul_info_all = pd.read_csv(file_haul_info_all, index_col=0) if file_haul_info_all.exists() else pd.DataFrame()

df_specimen_all = pd.concat([df_specimen_all, df_specimen], ignore_index=True)
df_length_all = pd.concat([df_length_all, df_length], ignore_index=True)
df_length_count_all = pd.concat([df_length_count_all, df_length_count], ignore_index=True)
df_haul_info_all = pd.concat([df_haul_info_all, df_info], ignore_index=True)

In [148]:
df_specimen_all

,SPECIMEN_ID,fork_length,organism_weight,sex,haul,length,time_stamp,Latitude,Longitude
0,119,28.8,0.130,Female,2,29,2025-06-14 19:05:54.064,33.158825,-117.435728
1,242,24.4,0.094,Male,2,24,2025-06-14 19:05:54.064,33.158825,-117.435728
2,262,30.5,0.174,Female,2,30,2025-06-14 19:05:54.064,33.158825,-117.435728
3,263,21.3,0.062,Female,2,21,2025-06-14 19:05:54.064,33.158825,-117.435728
4,282,19.9,0.052,Female,2,20,2025-06-14 19:05:54.064,33.158825,-117.435728
...,...,...,...,...,...,...,...,...,...
1570,18025,45.9,0.590,Male,40,46,2025-08-29 19:33:08.848,43.998004,-124.934579
1571,18026,38.5,0.410,Female,40,38,2025-08-29 19:33:08.848,43.998004,-124.934579
1572,18027,45.3,0.588,Male,40,45,2025-08-29 19:33:08.848,43.998004,-124.934579
1573,18028,37.8,0.342,Female,40,38,2025-08-29 19:33:08.848,43.998004,-124.934579
1574,18029,35.1,0.262,Male,40,35,2025-08-29 19:33:08.848,43.998004,-124.934579